name: cis-invitation-card

services:
  cis-invitation:
    build:
      context: .
      dockerfile: Dockerfile
    image: cis-invitation-card:latest
    container_name: cis-invitation-card
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - network_proxy

networks:
  network_proxy:
    external: true
